server:
  port: 8080

spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd'T'HH:mm:ss
    default-property-inclusion: non_null

# pop配置
biz:
  openapi:
    access:
      key: "xxxxxxx"
      secret: "xxxxxxx"
  live_mic:
    app_id: ${LIVE_MIC_APP_ID}
    app_key: ${LIVE_MIC_APP_KEY}
    gslb: https://gw.rtn.aliyuncs.com
  ai_aent:
    voice_chat_ai_agent_id: ${AI_AGENT_VOICE_CHAT_AI_AGENT_ID}
    avatar_ai_chat_3d_agent_id: "xxxxxx"
    vision_chat_ai_agent_id: "xxxxxx"
    region: ${AI_AGENT_REGION}
  voice:
    api_key: "xxxxxx"

http:
  cors:
    host: "*"